import {Link} from 'react-router';import {PublicNav} from '../components/PublicNav';import {Button} from '../components/ui/button';import {Card,CardContent} from '../components/ui/card';import {Search,Briefcase,Music,Users,CalendarDays,Zap,ShieldCheck,CheckCircle2} from 'lucide-react';
const paths=[
 {icon:Briefcase,title:'I want music work',text:'Create your professional profile, add 3–6 tagged work samples, set availability, then search jobs/gigs/auditions/sessions/tours. Apply with the most relevant proof.',steps:['Complete role, instruments, genres, city and rates','Add multiple samples—not one “everything” reel','Save searches and opportunities','Keep availability current','Track every application in Verse'],to:'/auth/jobseeker',cta:'Join as a professional'},
 {icon:Users,title:'I need to hire someone',text:'Use Talent Search for direct sourcing or post an opportunity when you want applications. Select 2–4 people to compare proof, rates and availability side by side.',steps:['Describe the actual role and commitment','Disclose pay/range where possible','Search in everyday language—Verse understands common music-industry synonyms','Compare candidates before messaging','Use folders for recurring talent pools'],to:'/auth/employer',cta:'Start hiring'},
 {icon:Users,title:'I have an event but I do not know the crew titles',text:'Use Build My Crew. Tell Verse the event type, city, audience size and whether you need music, sound, lights, video or production. Verse recommends a practical starting team.',steps:['Describe the event, not the job titles','Review required vs recommended roles','Adjust the lineup in Band Builder','Publish only the seats you need to fill','Keep one project record for the whole crew'],to:'/auth/employer',cta:'Sign in to build a crew'},
 {icon:Music,title:'I want to book live music',text:'Search acts rather than individual job applicants. Send event details, receive a quote, compare inclusions and lock the booking through the booking workflow.',steps:['Choose act type and city','Share date, venue, duration and audience','Confirm production/travel needs','Review quote validity and cancellation terms','Keep deposit/payment records tied to the booking'],to:'/book-music',cta:'Browse acts'},
 {icon:Zap,title:'I need someone urgently',text:'Urgent Replacement is intentionally short-form for cancellations and near-term gaps. Use it when response speed matters more than a full recruitment cycle.',steps:['State exact role/instrument','Add date/time and city','Give a realistic rate/budget','Mention travel/gear expectations','Close the request once filled'],to:'/music-professionals',cta:'Find professionals'}
];
export default function Guide(){return <div className="min-h-screen bg-slate-950 text-white"><PublicNav/><main className="max-w-6xl mx-auto px-5 py-14"><div className="max-w-3xl"><div className="text-violet-300 text-sm font-medium">5-minute guide</div><h1 className="text-4xl md:text-6xl font-bold mt-2">Get what you came for without learning the whole platform.</h1><p className="text-lg text-slate-400 mt-5 leading-8">Verse has many music-industry workflows, but you rarely need all of them. Pick your goal below and follow only that path.</p><div className="flex gap-2 mt-7"><Button asChild><Link to="/start">Choose my goal</Link></Button><Button variant="outline" asChild><Link to="/search"><Search size={16} className="mr-2"/>Search everything</Link></Button></div></div><div className="grid md:grid-cols-2 gap-5 mt-12">{paths.map(p=><Card key={p.title} className="bg-white/[.05] border-white/10"><CardContent className="p-6"><p.icon className="text-violet-300"/><h2 className="text-xl font-semibold mt-4">{p.title}</h2><p className="text-slate-400 mt-2 leading-6">{p.text}</p><div className="mt-5 space-y-2">{p.steps.map(x=><div key={x} className="flex gap-2 text-sm text-slate-300"><CheckCircle2 size={15} className="text-emerald-300 shrink-0 mt-0.5"/>{x}</div>)}</div><Button variant="secondary" className="mt-6" asChild><Link to={p.to}>{p.cta}</Link></Button></CardContent></Card>)}</div><section className="mt-14 rounded-2xl border border-white/10 bg-white/[.03] p-7"><div className="flex gap-3"><ShieldCheck className="text-emerald-300 shrink-0"/><div><h2 className="font-semibold text-xl">A simple rule for using Verse well</h2><p className="text-slate-400 mt-2 leading-7">Keep proof, availability, scope and money clear. A complete profile gets discovered more accurately; a clear opportunity gets better applicants; a clear booking brief gets better quotes. Avoid moving important commercial terms off-platform.</p></div></div></section></main></div>}
