import {useEffect,useMemo,useState} from 'react';
import {Navigation} from '../components/Navigation';
import {Input} from '../components/ui/input';
import {Button} from '../components/ui/button';
import {Card,CardContent} from '../components/ui/card';
import {Badge} from '../components/ui/badge';
import {Checkbox} from '../components/ui/checkbox';
import {Search,MapPin,Briefcase,Bookmark,BookmarkCheck,Bell,ShieldCheck,SlidersHorizontal} from 'lucide-react';
import {Link} from 'react-router';
import {apiDelete,apiGet,apiPost} from '../lib/api';
import {toast} from 'sonner';

const kinds=['','job','gig','audition','session','tour','internship','collaboration'];
const functions=['','Performance','Production','Audio Engineering','Live & Touring','A&R','Artist Management','Marketing & PR','Publishing & Rights','Label Operations','Music Tech'];
const workplaces=['','onsite','hybrid','remote','travel'];
const label=(s:string)=>s?s.replace(/(^|\s)\S/g,m=>m.toUpperCase()):'All';

export default function JobSearch(){
  const [jobs,setJobs]=useState<any[]>([]),[loading,setLoading]=useState(true),[showFilters,setShowFilters]=useState(false);
  const [f,setF]=useState({q:'',location:'',kind:'',functionArea:'',workplace:'',paid:false,verified:false});
  const set=(k:string,v:any)=>setF(x=>({...x,[k]:v}));
  const params=useMemo(()=>{const p=new URLSearchParams();Object.entries(f).forEach(([k,v])=>{if(v){const key=k==='functionArea'?'function':k;p.set(key,String(v))}});return p.toString()},[f]);
  async function load(){setLoading(true);try{const d=await apiGet<any>(`/jobs?${params}`);setJobs(d.jobs)}catch(e:any){toast.error(e.message)}finally{setLoading(false)}}
  useEffect(()=>{load()},[]);
  async function toggleSave(j:any){try{j.saved?await apiDelete(`/saved-jobs/${j.id}`):await apiPost(`/saved-jobs/${j.id}`);setJobs(xs=>xs.map(x=>x.id===j.id?{...x,saved:!x.saved}:x));toast.success(j.saved?'Removed from saved':'Saved for later')}catch(e:any){toast.error(e.message)}}
  async function createAlert(){try{await apiPost('/job-alerts',{name:f.q||f.kind||'Music opportunities',query:f.q,location:f.location,opportunityKind:f.kind,functionArea:f.functionArea,remoteOnly:f.workplace==='remote',frequency:'saved'});toast.success('Search saved to your account')}catch(e:any){toast.error(e.message)}}
  return <div className="min-h-screen bg-slate-950 text-white"><Navigation/><main className="max-w-7xl mx-auto px-5 md:px-6 pt-28 pb-16">
    <div className="flex flex-col lg:flex-row lg:items-end justify-between gap-5 mb-7"><div><div className="text-xs uppercase tracking-[.22em] text-violet-300 mb-2">Opportunities</div><h1 className="text-4xl md:text-5xl font-bold">Find work across the music industry</h1><p className="text-slate-400 mt-3 max-w-3xl">Jobs are only one format. Discover gigs, auditions, sessions, tours, internships and collaborations with clearer work terms and trust signals.</p></div><Button variant="outline" onClick={createAlert}><Bell className="w-4 h-4 mr-2"/>Save this search</Button></div>
    <Card className="bg-white/[.055] border-white/10 mb-7"><CardContent className="p-4 md:p-5"><form onSubmit={e=>{e.preventDefault();load()}} className="grid lg:grid-cols-[1.4fr_1fr_auto_auto] gap-3"><Input value={f.q} onChange={e=>set('q',e.target.value)} placeholder="Role, skill, company, instrument…" className="bg-black/20 border-white/15"/><Input value={f.location} onChange={e=>set('location',e.target.value)} placeholder="City, state or remote" className="bg-black/20 border-white/15"/><Button type="button" variant="outline" onClick={()=>setShowFilters(!showFilters)}><SlidersHorizontal className="w-4 h-4 mr-2"/>Filters</Button><Button><Search className="w-4 h-4 mr-2"/>Search</Button></form>
      {showFilters&&<div className="grid md:grid-cols-3 gap-3 mt-4 pt-4 border-t border-white/10"><select value={f.kind} onChange={e=>set('kind',e.target.value)} className="h-10 rounded-md bg-slate-900 border border-white/15 px-3">{kinds.map(x=><option key={x} value={x}>{x?label(x):'All opportunity types'}</option>)}</select><select value={f.functionArea} onChange={e=>set('functionArea',e.target.value)} className="h-10 rounded-md bg-slate-900 border border-white/15 px-3">{functions.map(x=><option key={x} value={x}>{x||'All functions'}</option>)}</select><select value={f.workplace} onChange={e=>set('workplace',e.target.value)} className="h-10 rounded-md bg-slate-900 border border-white/15 px-3">{workplaces.map(x=><option key={x} value={x}>{x?label(x):'Any workplace'}</option>)}</select><label className="flex items-center gap-2 text-sm text-slate-300"><Checkbox checked={f.paid} onCheckedChange={v=>set('paid',!!v)}/>Paid only</label><label className="flex items-center gap-2 text-sm text-slate-300"><Checkbox checked={f.verified} onCheckedChange={v=>set('verified',!!v)}/>Verified employers only</label></div>}
    </CardContent></Card>
    <div className="flex justify-between items-center mb-4"><div className="text-sm text-slate-400">{loading?'Searching…':`${jobs.length} opportunity${jobs.length===1?'':'ies'} found`}</div><Link to="/jobseeker/saved" className="text-sm text-violet-300 hover:text-violet-200">View saved opportunities</Link></div>
    {loading?<div className="grid gap-4">{[1,2,3].map(x=><div key={x} className="h-44 rounded-2xl bg-white/[.04] animate-pulse"/>)}</div>:jobs.length===0?<Card className="bg-white/5 border-white/10"><CardContent className="p-12 text-center"><h3 className="font-semibold text-lg">No exact matches</h3><p className="text-slate-400 mt-2">Try a wider location, fewer filters, or save this search as an alert.</p></CardContent></Card>:<div className="grid gap-4">{jobs.map(j=><Card key={j.id} className="bg-white/[.055] border-white/10 hover:bg-white/[.075] transition"><CardContent className="p-5 md:p-6"><div className="flex gap-4 justify-between"><Link className="min-w-0 flex-1" to={`/jobseeker/jobs/${j.id}`}><div className="flex flex-wrap items-center gap-2 mb-2"><Badge variant="secondary">{label(j.opportunity_kind||'job')}</Badge>{j.employerVerified&&<Badge className="bg-emerald-500/15 text-emerald-300 border-emerald-400/20"><ShieldCheck size={13} className="mr-1"/>Verified</Badge>}{j.featured&&<Badge>Featured</Badge>}{j.fitScore&&<Badge className="bg-sky-500/15 text-sky-200 border-sky-400/20">{j.fitScore}% profile fit</Badge>}</div><h2 className="text-xl md:text-2xl font-semibold truncate">{j.title}</h2><p className="text-violet-300 mt-1">{j.company}</p><div className="text-sm text-slate-400 mt-3 flex flex-wrap gap-x-4 gap-y-2"><span className="flex items-center"><MapPin className="w-4 h-4 mr-1"/>{j.location}</span><span className="flex items-center"><Briefcase className="w-4 h-4 mr-1"/>{label(j.workplace||j.type)}</span>{j.function_area&&<span>{j.function_area}</span>}<span>{j.genre}</span></div><div className="flex flex-wrap gap-2 mt-4">{j.skills?.slice(0,6).map((s:string)=><Badge variant="outline" key={s} className="border-white/15 text-slate-300">{s}</Badge>)}</div></Link><div className="flex flex-col items-end gap-3"><Button aria-label="Save job" size="icon" variant="ghost" onClick={()=>toggleSave(j)}>{j.saved?<BookmarkCheck className="text-violet-300"/>:<Bookmark/>}</Button><div className="text-right hidden sm:block"><div className="font-semibold text-sm">{j.salary||((j.compensation_min||j.compensation_max)?`${j.currency||'INR'} ${j.compensation_min||''}${j.compensation_max?`–${j.compensation_max}`:''}`:'Compensation not disclosed')}</div><div className="text-xs text-slate-500 mt-1">{j.applicationsCount} applicant{j.applicationsCount===1?'':'s'}</div></div></div></div></CardContent></Card>)}</div>}
  </main></div>
}
