import { Link } from 'react-router';
import { ArrowRight, AudioLines, BadgeCheck, BriefcaseBusiness, CalendarDays, CheckCircle2, Headphones, MapPin, MessageSquare, Mic2, Radio, Search, ShieldCheck, Sparkles, Star, Users, WandSparkles, Zap } from 'lucide-react';
import { Button } from '../components/ui/button';
import { Card, CardContent } from '../components/ui/card';
import { BrandMark } from '../components/BrandMark';
import { SkipLink } from '../components/SkipLink';

const formats = [['Jobs', BriefcaseBusiness], ['Gigs', Zap], ['Auditions', Mic2], ['Sessions', Headphones], ['Tours', MapPin], ['Collaborations', Users]] as const;
const roles = [
  ['Artists & performers', Mic2, 'Live, studio and screen', 'performer'],
  ['Producers & engineers', AudioLines, 'Recording, mix and mastering', 'engineer'],
  ['A&R & label teams', Star, 'Discovery and development', 'A&R'],
  ['Managers & artist services', Users, 'Careers and operations', 'manager'],
  ['Live & touring crews', Radio, 'Stage, sound and production', 'live'],
  ['Music-tech professionals', WandSparkles, 'Products powering music', 'music-tech']
] as const;

export default function LandingPage() {
  return <div className="min-h-screen overflow-hidden bg-slate-950 text-white">
    <SkipLink />
    <header className="fixed inset-x-0 top-0 z-50 border-b border-white/10 bg-[#070813]/80 backdrop-blur-2xl">
      <div className="mx-auto flex h-[72px] max-w-7xl items-center justify-between px-5 md:px-6">
        <Link to="/" aria-label="Verse home"><BrandMark /></Link>
        <nav className="flex items-center gap-1" aria-label="Primary navigation">
          <Button variant="ghost" className="hidden lg:inline-flex" asChild><Link to="/music-jobs"><Search size={16} className="mr-2" />Find work</Link></Button>
          <Button variant="ghost" className="hidden md:inline-flex" asChild><Link to="/book-music"><CalendarDays size={16} className="mr-2" />Book music</Link></Button>
          <Button variant="ghost" className="hidden sm:inline-flex" asChild><Link to="/guide">How it works</Link></Button>
          <Button variant="ghost" asChild><Link to="/auth/jobseeker">Sign in</Link></Button>
          <Button className="border-0 bg-gradient-to-r from-fuchsia-500 to-violet-500 shadow-lg shadow-violet-950/40" asChild><Link to="/start">Join Verse <ArrowRight size={16} className="ml-2" /></Link></Button>
        </nav>
      </div>
    </header>

    <main>
      <section className="relative px-5 pb-24 pt-32 md:px-6 md:pb-28 md:pt-40">
        <div className="verse-grid absolute inset-0 pointer-events-none" />
        <div className="verse-orb absolute -left-36 -top-44 h-[34rem] w-[34rem] rounded-full bg-fuchsia-600/60" />
        <div className="verse-orb absolute -right-40 top-16 h-[32rem] w-[32rem] rounded-full bg-cyan-500/35 [animation-delay:-4s]" />
        <div className="relative mx-auto grid max-w-7xl items-center gap-16 lg:grid-cols-[1.04fr_.96fr]">
          <div>
            <div className="mb-6 inline-flex items-center gap-2 rounded-full border border-fuchsia-300/25 bg-fuchsia-400/10 px-3.5 py-2 text-sm font-semibold text-fuchsia-100 shadow-lg shadow-fuchsia-950/20"><Sparkles size={15} className="text-fuchsia-300" /> The network built for people who make music happen</div>
            <h1 className="max-w-4xl text-5xl font-black leading-[.98] tracking-[-.055em] sm:text-6xl md:text-7xl xl:text-[5.35rem]">Your next move in music <span className="verse-gradient-text">starts here.</span></h1>
            <p className="mt-7 max-w-2xl text-lg leading-8 text-slate-300 md:text-xl">Find serious opportunities, showcase real credits, book trusted talent and move every collaboration from first listen to final hire.</p>
            <div className="mt-9 flex flex-col gap-3 sm:flex-row">
              <Button size="lg" className="h-12 w-full border-0 bg-gradient-to-r from-fuchsia-500 via-violet-500 to-indigo-500 px-7 text-base shadow-xl shadow-violet-950/50 sm:w-auto" asChild><Link to="/start">Find my path <ArrowRight size={18} className="ml-2" /></Link></Button>
              <Button size="lg" variant="outline" className="h-12 w-full border-white/20 bg-white/[.055] px-7 text-base sm:w-auto" asChild><Link to="/search"><Search size={18} className="mr-2" />Search the network</Link></Button>
            </div>
            <div className="mt-10 flex flex-wrap gap-2.5">{formats.map(([label, Icon]) => <Link to={label === 'Collaborations' ? '/music-professionals' : `/music-jobs?kind=${label.toLowerCase()}`} key={label} className="group inline-flex items-center gap-2 rounded-full border border-white/15 bg-white/[.055] px-3.5 py-2 text-sm text-slate-300 hover:border-violet-300/40 hover:bg-violet-400/10 hover:text-white"><Icon size={14} className="text-violet-300" />{label}</Link>)}</div>
          </div>
          <HeroStage />
        </div>
        <div className="relative mx-auto mt-20 grid max-w-7xl grid-cols-2 gap-3 border-y border-white/10 py-6 md:grid-cols-4"><Proof value="One profile" label="for every kind of music work" /><Proof value="Clear terms" label="pay, timing and expectations" /><Proof value="Real proof" label="credits, reels and work samples" /><Proof value="Built-in trust" label="verification and moderation" /></div>
      </section>

      <section className="border-y border-white/10 bg-white/[.025] px-5 py-20 md:px-6"><div className="mx-auto max-w-7xl">
        <SectionIntro eyebrow="One network. Every working rhythm." title="Music careers do not fit into one job form." body="Verse understands the difference between a two-hour session, a touring contract, an audition, a permanent role and a new band looking for its missing member." />
        <div className="mt-10 grid gap-4 md:grid-cols-3"><Value icon={Search} color="text-cyan-300" title="Opportunity, with context" text="Search roles, formats, genres, locations, availability and pay without guessing what the brief really means." /><Value icon={AudioLines} color="text-fuchsia-300" title="Proof people can hear" text="Lead with credits, reels, repertoire and work samples—signals that matter more than generic buzzwords." /><Value icon={ShieldCheck} color="text-emerald-300" title="Trust in every workflow" text="Verification, moderation, reporting, audit trails and review controls are part of the product, not an afterthought." /></div>
      </div></section>

      <section className="mx-auto max-w-7xl px-5 py-24 md:px-6"><div className="grid items-center gap-14 lg:grid-cols-2">
        <div><div className="mb-3 flex items-center gap-2 text-xs font-bold uppercase tracking-[.22em] text-fuchsia-300"><Mic2 size={15} /> For professionals</div><h2 className="text-4xl font-black tracking-tight md:text-5xl">Make your work impossible to overlook.</h2><p className="mt-5 text-lg leading-8 text-slate-300">Build a career identity around what you have actually done—and what you want to do next.</p><div className="mt-7 grid gap-3 sm:grid-cols-2"><Point text="Structured credits and portfolio proof" /><Point text="Music-specific discovery and alerts" /><Point text="Application and audition tracking" /><Point text="Availability, booking and messaging" /></div><Button className="mt-8 bg-fuchsia-600 hover:bg-fuchsia-500" asChild><Link to="/auth/jobseeker">Build my profile <ArrowRight size={16} className="ml-2" /></Link></Button></div>
        <TalentCard />
      </div></section>

      <section className="border-y border-white/10 bg-white/[.025] px-5 py-24 md:px-6"><div className="mx-auto grid max-w-7xl items-center gap-14 lg:grid-cols-2">
        <HiringCard />
        <div><div className="mb-3 flex items-center gap-2 text-xs font-bold uppercase tracking-[.22em] text-cyan-300"><BriefcaseBusiness size={15} /> For hiring teams</div><h2 className="text-4xl font-black tracking-tight md:text-5xl">Hire with signal, not inbox chaos.</h2><p className="mt-5 text-lg leading-8 text-slate-300">Create clearer briefs, find talent by real music signals and move candidates through one visible pipeline.</p><div className="mt-7 space-y-3"><Point text="Music-specific opportunity briefs" /><Point text="Searchable portfolios and credits" /><Point text="Shortlists, comparisons and hiring stages" /><Point text="Conversation history tied to the opportunity" /></div><Button className="mt-8 bg-cyan-400 text-slate-950 hover:bg-cyan-300" asChild><Link to="/auth/employer">Start hiring <ArrowRight size={16} className="ml-2" /></Link></Button></div>
      </div></section>

      <section className="mx-auto max-w-7xl px-5 py-24 md:px-6"><SectionIntro eyebrow="The whole industry" title="A network as varied as the music itself." body="Creative, commercial, technical and operational people all need a professional home." centered /><div className="mt-10 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{roles.map(([label, Icon, sub, role]) => <Link key={label} to={`/music-professionals?role=${encodeURIComponent(role)}`} className="verse-card-lift verse-surface group flex items-center gap-4 rounded-2xl p-5"><span className="grid h-12 w-12 shrink-0 place-items-center rounded-xl bg-gradient-to-br from-violet-500/25 to-cyan-400/10 text-violet-200"><Icon size={21} /></span><span><span className="block font-bold text-white">{label}</span><span className="mt-1 block text-sm text-slate-400">{sub}</span></span><ArrowRight size={17} className="ml-auto text-slate-500 group-hover:translate-x-1 group-hover:text-white" /></Link>)}</div></section>

      <section className="px-5 pb-24 md:px-6"><div className="relative mx-auto max-w-7xl overflow-hidden rounded-[2rem] border border-violet-300/25 bg-gradient-to-br from-fuchsia-500/20 via-violet-500/15 to-cyan-400/10 p-8 shadow-2xl shadow-violet-950/30 md:p-14"><div className="verse-grid absolute inset-0" /><div className="relative flex flex-col justify-between gap-8 lg:flex-row lg:items-center"><div><div className="mb-3 flex items-center gap-2 text-sm font-bold text-fuchsia-200"><Sparkles size={17} /> Your next chapter needs a first move</div><h2 className="max-w-2xl text-3xl font-black tracking-tight md:text-5xl">Come for the opportunity. Stay for the network.</h2></div><div className="flex shrink-0 flex-col gap-3 sm:flex-row"><Button size="lg" asChild><Link to="/auth/jobseeker">Join as professional</Link></Button><Button size="lg" variant="outline" className="border-white/20 bg-white/[.05]" asChild><Link to="/auth/employer">Join as employer</Link></Button></div></div></div></section>
    </main>

    <footer className="border-t border-white/10 px-5 py-9 md:px-6"><div className="mx-auto flex max-w-7xl flex-col justify-between gap-6 text-sm text-slate-400 md:flex-row md:items-center"><BrandMark /><div className="flex flex-wrap gap-x-5 gap-y-2"><Link to="/guide">Guide</Link><Link to="/privacy">Privacy</Link><Link to="/terms">Terms</Link><Link to="/safety">Safety</Link><Link to="/sitemap">Site map</Link><Link to="/contact">Contact</Link></div></div></footer>
  </div>;
}

function HeroStage() { return <div className="relative mx-auto w-full max-w-[540px] lg:mx-0"><div className="absolute -inset-8 rounded-[3rem] bg-gradient-to-br from-fuchsia-500/20 via-violet-500/10 to-cyan-400/20 blur-2xl" /><div className="verse-surface relative overflow-hidden rounded-[1.8rem] p-4 md:p-5"><div className="flex items-center justify-between border-b border-white/10 pb-4"><div className="flex items-center gap-2"><span className="h-2.5 w-2.5 rounded-full bg-rose-400" /><span className="h-2.5 w-2.5 rounded-full bg-amber-300" /><span className="h-2.5 w-2.5 rounded-full bg-emerald-300" /></div><span className="flex items-center gap-2 text-xs font-semibold text-slate-400"><span className="h-2 w-2 animate-pulse rounded-full bg-emerald-300" /> Live network</span></div><div className="mt-5 rounded-2xl border border-fuchsia-300/20 bg-gradient-to-br from-fuchsia-500/15 to-violet-500/[.06] p-5"><div className="flex items-start justify-between gap-3"><div><span className="text-[11px] font-bold uppercase tracking-[.16em] text-fuchsia-200">Example opportunity</span><h3 className="mt-2 text-xl font-black">Playback vocalist · Feature film</h3><p className="mt-1 flex items-center text-sm text-slate-300"><MapPin size={14} className="mr-1.5" /> Mumbai · Studio session</p></div><div className="verse-equalizer" aria-hidden="true">{[1,2,3,4,5].map(x=><span key={x} />)}</div></div><div className="mt-5 flex flex-wrap gap-2"><Tag>₹25k–₹40k</Tag><Tag>Hindi</Tag><Tag>Verified</Tag></div><div className="mt-5 flex items-center justify-between border-t border-white/10 pt-4"><div className="flex -space-x-2">{['AS','RK','NM'].map((x,i)=><span key={x} className={`grid h-8 w-8 place-items-center rounded-full border-2 border-[#121326] text-[10px] font-bold ${['bg-fuchsia-500','bg-violet-500','bg-cyan-500'][i]}`}>{x}</span>)}</div><span className="text-xs text-slate-400">12 professionals matched</span></div></div><div className="mt-3 grid grid-cols-2 gap-3"><Metric icon={AudioLines} value="86%" label="Profile strength" color="text-cyan-300 bg-cyan-400/15" /><Metric icon={MessageSquare} value="4" label="New conversations" color="text-fuchsia-300 bg-fuchsia-400/15" /></div></div><div className="verse-surface absolute -bottom-7 -left-4 hidden items-center gap-3 rounded-2xl px-4 py-3 shadow-2xl sm:flex"><span className="grid h-10 w-10 place-items-center rounded-xl bg-emerald-400/15 text-emerald-300"><BadgeCheck size={20} /></span><span><span className="block text-sm font-bold">Credit verified</span><span className="block text-xs text-slate-400">Studio album · 2026</span></span></div></div>; }
function Metric({icon:Icon,value,label,color}:{icon:any;value:string;label:string;color:string}) { return <div className="rounded-2xl border border-white/10 bg-white/[.045] p-4"><span className={`grid h-9 w-9 place-items-center rounded-xl ${color}`}><Icon size={17} /></span><div className="mt-4 text-2xl font-black">{value}</div><div className="text-xs text-slate-400">{label}</div></div>; }
function TalentCard() { return <Card className="verse-surface overflow-hidden rounded-3xl border-white/15 bg-transparent"><div className="h-28 bg-gradient-to-r from-fuchsia-500/40 via-violet-500/35 to-cyan-400/30" /><CardContent className="relative p-6 md:p-8"><div className="absolute -top-10 grid h-20 w-20 place-items-center rounded-2xl border-4 border-[#10111f] bg-gradient-to-br from-fuchsia-500 to-violet-600 text-2xl font-black shadow-xl">AS</div><div className="flex justify-end"><BadgeCheck className="text-emerald-300" /></div><h3 className="mt-3 text-2xl font-black">Aditya Sharma</h3><div className="mt-1 text-fuchsia-200">Example · Playback singer</div><div className="mt-6 grid grid-cols-2 gap-3"><Mini k="Base" v="Mumbai" /><Mini k="Genres" v="Bollywood · Pop" /><Mini k="Open to" v="Sessions · Film" /><Mini k="Languages" v="Hindi · English" /></div><div className="mt-6 text-xs font-bold uppercase tracking-[.16em] text-slate-400">Selected proof</div>{['Feature-film playback credit','Studio vocal reel','Live performance showreel'].map(x=><div key={x} className="flex items-center gap-2 border-b border-white/10 py-3 text-sm"><CheckCircle2 size={15} className="text-emerald-300" />{x}</div>)}</CardContent></Card>; }
function HiringCard() { return <Card className="verse-surface order-2 overflow-hidden rounded-3xl border-white/15 bg-transparent lg:order-1"><CardContent className="p-6 md:p-8"><div className="flex items-start gap-3"><span className="grid h-12 w-12 shrink-0 place-items-center rounded-xl bg-cyan-400/15 text-cyan-300"><BriefcaseBusiness /></span><div><div className="text-xs font-bold uppercase tracking-[.16em] text-cyan-200">Example pipeline</div><h3 className="mt-1 text-xl font-black">Session bassist — Indie EP</h3><div className="mt-1 text-sm text-slate-400">Mumbai · Onsite · Paid per session</div></div></div><div className="mt-5 flex flex-wrap gap-2"><Tag>Session</Tag><Tag>Performance</Tag><Tag>Verified employer</Tag></div><div className="mt-6 grid grid-cols-3 gap-3 text-center"><Mini k="Applicants" v="12" /><Mini k="Shortlisted" v="4" /><Mini k="Interview" v="2" /></div><div className="mt-6 space-y-2">{['Rhea Kapoor','Kabir Mehta','Neel Arora'].map((x,i)=><div key={x} className="flex items-center rounded-xl border border-white/10 bg-white/[.04] px-3 py-3"><span className={`mr-3 grid h-8 w-8 place-items-center rounded-lg text-xs font-bold ${['bg-fuchsia-500/30','bg-violet-500/30','bg-cyan-500/25'][i]}`}>{x.split(' ').map(v=>v[0]).join('')}</span><span className="text-sm font-semibold">{x}</span><span className="ml-auto text-xs text-slate-400">{[92,88,84][i]}% fit</span></div>)}</div></CardContent></Card>; }
function Value({ icon: Icon, color, title, text }: { icon:any; color:string; title:string; text:string }) { return <div className="verse-card-lift verse-surface rounded-2xl p-6"><span className={`grid h-11 w-11 place-items-center rounded-xl bg-white/[.06] ${color}`}><Icon size={20} /></span><h3 className="mt-5 text-xl font-black">{title}</h3><p className="mt-2 leading-7 text-slate-300">{text}</p></div>; }
function Point({ text }: { text:string }) { return <div className="flex gap-3 rounded-xl border border-white/10 bg-white/[.035] p-3.5 text-sm text-slate-300"><CheckCircle2 size={18} className="mt-0.5 shrink-0 text-emerald-300" /><span>{text}</span></div>; }
function Mini({ k, v }: { k:string; v:string }) { return <div className="rounded-xl border border-white/10 bg-black/15 p-3"><div className="text-[10px] font-bold uppercase tracking-[.14em] text-slate-400">{k}</div><div className="mt-1 text-sm font-semibold text-white">{v}</div></div>; }
function Tag({ children }: { children:React.ReactNode }) { return <span className="rounded-full border border-white/10 bg-white/[.06] px-2.5 py-1 text-xs text-slate-300">{children}</span>; }
function Proof({ value, label }: { value:string; label:string }) { return <div className="px-3 md:px-5"><div className="font-black text-white">{value}</div><div className="mt-1 text-xs leading-5 text-slate-400">{label}</div></div>; }
function SectionIntro({ eyebrow, title, body, centered=false }: { eyebrow:string; title:string; body:string; centered?:boolean }) { return <div className={`max-w-3xl ${centered?'mx-auto text-center':''}`}><div className="text-xs font-bold uppercase tracking-[.22em] text-violet-300">{eyebrow}</div><h2 className="mt-3 text-4xl font-black tracking-tight md:text-5xl">{title}</h2><p className="mt-4 text-lg leading-8 text-slate-300">{body}</p></div>; }
