version: 2
updates:
  - package-ecosystem: npm
    directory: /
    target-branch: production
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 3
    groups:
      npm-minor-and-patch:
        update-types: [minor, patch]

  - package-ecosystem: bundler
    directory: /backend
    target-branch: production
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 3
    groups:
      bundler-minor-and-patch:
        update-types: [minor, patch]

  - package-ecosystem: github-actions
    directory: /
    target-branch: production
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 2
