source "https://rubygems.org"

ruby "3.3.6"

gem "rails", "~> 8.1.4"
gem "json", "~> 2.10"
gem "pg", "~> 1.5"
gem "puma", "~> 8.0"
gem "bcrypt", "~> 3.1"
gem "rack-cors", "~> 3.0"
gem "aws-sdk-s3", require: false
gem "faraday", "~> 2.12"
gem "redis", "~> 5.2"
gem "good_job", "~> 4.13"
gem "sentry-ruby", "~> 7.0"
gem "sentry-rails", "~> 7.0"
gem "bootsnap", require: false

group :development, :test do
  gem "debug", platforms: %i[mri windows], require: "debug/prelude"
  gem "brakeman", require: false
  gem "bundler-audit", require: false
end
