source "https://rubygems.org"

ruby "3.3.6"

gem "rails", "~> 7.2.2"
gem "pg", "~> 1.5"
gem "puma", ">= 6.4"
gem "bcrypt", "~> 3.1"
gem "rack-cors", "~> 2.0"
gem "aws-sdk-s3", require: false
gem "bootsnap", require: false

group :development, :test do
  gem "debug", platforms: %i[mri windows], require: "debug/prelude"
end

