const base=(process.env.ELASTICSEARCH_URL||'').replace(/\/$/,'');
const prefix=process.env.ELASTICSEARCH_INDEX_PREFIX||'verse';
const enabled=()=>Boolean(base);
const headers=()=>({'content-type':'application/json',...(process.env.ELASTICSEARCH_API_KEY?{'authorization':`ApiKey ${process.env.ELASTICSEARCH_API_KEY}`}:{})});
async function es(path,options={}){if(!enabled())throw new Error('Elasticsearch not configured');const r=await fetch(`${base}${path}`,{...options,headers:{...headers(),...(options.headers||{})}});if(!r.ok)throw new Error(`Elasticsearch ${r.status}: ${await r.text()}`);return r.status===204?{}:r.json();}
const indexFor=(type)=>`${prefix}-${type}`;
export async function indexSearchDocument(type,id,document){if(!enabled())return {indexed:false,reason:'not_configured'};try{await es(`/${indexFor(type)}/_doc/${encodeURIComponent(id)}?refresh=false`,{method:'PUT',body:JSON.stringify({...document,id,type,indexedAt:new Date().toISOString()})});return {indexed:true};}catch(e){console.error('search index failed',type,id,e.message);return {indexed:false,reason:e.message};}}
export async function deleteSearchDocument(type,id){if(!enabled())return {deleted:false};try{await es(`/${indexFor(type)}/_doc/${encodeURIComponent(id)}`,{method:'DELETE'});return {deleted:true};}catch(e){return {deleted:false,reason:e.message};}}
export async function bulkReindex(documents){if(!enabled())return {indexed:false,reason:'not_configured',count:0};const lines=[];for(const d of documents){lines.push(JSON.stringify({index:{_index:indexFor(d.type),_id:d.id}}));lines.push(JSON.stringify({...d.document,id:d.id,type:d.type,indexedAt:new Date().toISOString()}));}if(!lines.length)return {indexed:true,count:0};const r=await fetch(`${base}/_bulk`,{method:'POST',headers:{...headers(),'content-type':'application/x-ndjson'},body:lines.join('\n')+'\n'});if(!r.ok)throw new Error(`Elasticsearch bulk ${r.status}: ${await r.text()}`);const out=await r.json();return {indexed:!out.errors,count:documents.length,errors:out.errors};}
export async function elasticSearch(query,{types=['jobs','talent','acts','samples'],limit=30,filters={}}={}){if(!enabled())return null;const should=[{multi_match:{query,fields:['title^4','name^4','headline^3','roleNames^3','instrumentNames^3','tags^3','genres^2','skills^2','description','bio','city','company'],type:'best_fields',fuzziness:'AUTO'}}];if(!query)should.splice(0,1,{match_all:{}});const filter=[];for(const [field,value] of Object.entries(filters)){if(value!==undefined&&value!==null&&value!=='')filter.push({term:{[field]:value}});}const body={size:Math.min(100,Math.max(1,limit)),query:{bool:{must:should,filter}},highlight:{fields:{title:{},name:{},headline:{},description:{fragment_size:120,number_of_fragments:1},bio:{fragment_size:120,number_of_fragments:1}}}};try{const data=await es(`/${types.map(indexFor).join(',')}/_search`,{method:'POST',body:JSON.stringify(body)});return (data.hits?.hits||[]).map(h=>({...h._source,_score:h._score,highlight:h.highlight||{}}));}catch(e){console.error('elastic search failed',e.message);return null;}}
export function searchStatus(){return {enabled:enabled(),provider:enabled()?'elasticsearch':'sqlite-fallback',urlConfigured:Boolean(base),indexPrefix:prefix};}
