import {ExternalLink,FileText,Music,Video} from 'lucide-react';
import {Badge} from './ui/badge';

type Sample={id?:string;title:string;url:string;type?:string;description?:string;thumbnailUrl?:string;waveformUrl?:string;mediaMetadata?:any;tags?:string[];genres?:string[];roles?:string[];instruments?:string[];creditedAs?:string;year?:number};
const abs=(u?:string)=>!u?'':u.startsWith('/uploads/')?u:u;
export function WorkSamplePlayer({sample,compact=false}:{sample:Sample;compact?:boolean}){
  const t=(sample.type||'').toLowerCase(),isAudio=t==='audio'||/\.(mp3|wav|m4a)(\?|$)/i.test(sample.url),isVideo=['video','live','showreel'].includes(t)||/\.(mp4|webm)(\?|$)/i.test(sample.url),isPdf=/\.pdf(\?|$)/i.test(sample.url);let embed='';try{const u=new URL(sample.url);if(/(^|\.)youtu\.?be$/.test(u.hostname)||u.hostname.includes('youtube.com')){const id=u.hostname.includes('youtu.be')?u.pathname.slice(1):u.searchParams.get('v')||u.pathname.split('/').filter(Boolean).pop();if(id)embed=`https://www.youtube.com/embed/${encodeURIComponent(id)}`}else if(u.hostname.includes('spotify.com'))embed=`https://open.spotify.com/embed${u.pathname}`;else if(u.hostname.includes('soundcloud.com'))embed=`https://w.soundcloud.com/player/?url=${encodeURIComponent(sample.url)}&auto_play=false`; }catch{}
  return <div className="rounded-xl border border-white/10 bg-black/20 overflow-hidden">
    {embed?<iframe title={sample.title} src={embed} loading="lazy" allow="autoplay; encrypted-media; picture-in-picture" className="w-full h-52 border-0 bg-black"/>:isVideo?<video controls preload="metadata" poster={sample.thumbnailUrl||undefined} className="w-full max-h-80 bg-black" src={abs(sample.url)}/>:isAudio?<div className="p-4">{sample.waveformUrl&&<img src={abs(sample.waveformUrl)} alt="Audio waveform" className="w-full h-20 object-cover opacity-70 rounded-lg mb-3"/>}<audio controls preload="metadata" className="w-full" src={abs(sample.url)}/></div>:sample.thumbnailUrl?<img src={abs(sample.thumbnailUrl)} alt="" className="w-full max-h-64 object-cover"/>:null}
    <div className={compact?'p-3':'p-4'}><div className="flex gap-3 items-start"><div className="mt-0.5 text-violet-300">{isAudio?<Music size={17}/>:isVideo?<Video size={17}/>:<FileText size={17}/>}</div><div className="min-w-0 flex-1"><div className="font-medium">{sample.title}</div>{(sample.creditedAs||sample.year)&&<div className="text-xs text-violet-300 mt-1">{[sample.creditedAs,sample.year].filter(Boolean).join(' · ')}</div>}{!compact&&sample.description&&<p className="text-sm text-slate-400 mt-2 line-clamp-3">{sample.description}</p>}<div className="flex flex-wrap gap-1 mt-2">{[...(sample.roles||[]),...(sample.genres||[]),...(sample.instruments||[]),...(sample.tags||[])].slice(0,8).map(x=><Badge key={x} variant="secondary">{x}</Badge>)}</div></div><a href={sample.url} target="_blank" rel="noreferrer" className="text-slate-400 hover:text-white" title={isPdf?'Open document':'Open source'}><ExternalLink size={16}/></a></div></div>
  </div>
}
